/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.robjwells.adventofcode2015;

public class App {
    private final static Solution[] days = {

    };

    public static void main(String[] args) {
    }
}
